dist: xenial
language: python
cache: pip
stages:
  - name: static analysis
  - name: test
python:
  - "3.6"
  - "3.7"
install:
  - "pip install -r requirements.txt"
  - "pip install -r requirements_tests.txt"
  - "pip install docutils"
  - "pip install -e ."
script:
  - pytest --cov=.
  - python setup.py check --restructuredtext --strict
  - rst2html.py --halt=2 README.rst >/dev/null
after_success:
  - codecov
jobs:
  include:
      - stage: static analysis
        python: "3.7"
        script: black . --diff
        after_success: skip
