dist: xenial
language: python
cache: pip
matrix:
  include:
  - name: static analysis
    python: "3.7"
    install: pip install .[dev,doc]
    script:
    - black . --check --diff
    - python setup.py check --restructuredtext --strict
    - rst2html.py --halt=2 README.rst >/dev/null
    after_success: skip
python:
- "3.6"
- "3.7"
install:
- pip install -e .[dev,doc,test]
script:
- pytest --cov=. --cov-report=xml
after_success:
- python-codacy-coverage -r coverage.xml
