dist: xenial
language: python
cache: pip
matrix:
  include:
    - name: "static analysis"
      python: "3.7"
      install: pip install black
      script: black . --check --diff
      after_success: skip
python:
  - "3.6"
  - "3.7"
install:
  - "pip install -r requirements.txt"
  - "pip install docutils"
  - "pip install -e ."
  - "pip install -r requirements_tests.txt"
script:
  - pytest --cov=. --cov-report=xml
  - python setup.py check --restructuredtext --strict
  - rst2html.py --halt=2 README.rst >/dev/null
after_success:
  - python-codacy-coverage -r coverage.xml
