name: Label & close stale issues
on:
  schedule:
    - cron: "30 1 * * 1,2,3,4,5"
  workflow_dispatch:

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - name: Label stale issues
        uses: actions/stale@v10
        with:
          days-before-issue-stale: 60
          days-before-pr-stale: -1 # We don't want to mark PRs as stale
          days-before-close: -1 # We don't want to close issues in this action
          stale-issue-label: stale
          only-issue-types: Bug
          exempt-issue-labels: pinned
          stale-issue-message: |
            This issue has been automatically marked as stale because it has not had recent activity.
            Please add a comment if you want to keep the issue open. Thank you for your contributions!
          debug-only: false # set to `true` to enable dry-run
      - name: Close stale issues
        uses: actions/stale@v10
        with:
          days-before-issue-stale: -1 # We don't want to mark issues as stale in this action
          days-before-issue-close: 14
          days-before-pr-close: -1 # don't close PRs
          days-before-pr-stale: -1 # don't mark PRs as stale
          stale-issue-label: stale
          any-of-labels: Needs info‚ùî
          debug-only: true # enable dry-run, remove when we know from the logs it's working.
